image: node:9.10.1

cache:
  paths:
  - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script: npm install

test:
  stage: test
  script: npm test
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
